/*
 * generated by Xtext
 */
package com.telefonica.ietf.nemo.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractNemoDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.telefonica.ietf.nemo.nemoDSL.NemoDSLPackage.eINSTANCE);
		return result;
	}
}
