/*
 * generated by Xtext
 */
package com.telefonica.ietf.nemo;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class NemoDSLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return com.telefonica.ietf.nemo.ui.internal.NemoDSLActivator.getInstance().getInjector("com.telefonica.ietf.nemo.NemoDSL");
	}
	
}
