/**
 * generated by Xtext
 */
package com.telefonica.ietf.nemo.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
@SuppressWarnings("all")
public class NemoDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
