/**
 * generated by Xtext
 */
package com.telefonica.ietf.nemo.validation;

import com.telefonica.ietf.nemo.validation.AbstractNemoDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class NemoDSLValidator extends AbstractNemoDSLValidator {
}
