/*
 * generated by Xtext
 */
package com.telefonica.ietf.nemo.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.telefonica.ietf.nemo.services.NemoDSLGrammarAccess;

public class NemoDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private NemoDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.telefonica.ietf.nemo.parser.antlr.internal.InternalNemoDSLParser createParser(XtextTokenStream stream) {
		return new com.telefonica.ietf.nemo.parser.antlr.internal.InternalNemoDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "NemoFile";
	}
	
	public NemoDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(NemoDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
