/*
 * generated by Xtext
 */
package com.telefonica.ietf.nemo.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class NemoDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/telefonica/ietf/nemo/parser/antlr/internal/InternalNemoDSL.tokens");
	}
}
