/*
 * generated by Xtext
 */
package com.telefonica.ietf.nemo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class NemoDSLUiModule extends com.telefonica.ietf.nemo.ui.AbstractNemoDSLUiModule {
	public NemoDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
