/*
 * generated by Xtext
 */
package com.telefonica.ietf.nemo;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NemoDSLRuntimeModule extends com.telefonica.ietf.nemo.AbstractNemoDSLRuntimeModule {

}
